theme: jekyll-theme-dinky
url: "https://gerardon.github.io/"
repository: "gerardon/gerardon.github.io"
logo: "/assets/img/avatar.png"
title: "cv.md"
description: "Gerardo Nobre Soares"
show_downloads: false
